version: "3.8"
services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rag_chatbot
      - text_to_sql
    environment:
      - RAG_URL=http://rag_chatbot:8001
      - TEXT_TO_SQL_URL = http://rag_chatbot:8002
    networks:
      - app-network

  rag_chatbot:
    build: ./rag_chatbot
    ports:
      -"8001:8001"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - app-network
    
  text_to_sql:
    build: ./text_to_sql
    ports:
      -"8002:8002"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: brigde
    